stages:
  - pull
  - deploy


pull_galleries:
  stage: pull
  script: sh ./build.sh
  artifacts:
    paths:
      - public
  only: 
    - web

deploy:
  stage: deploy
  variables:
    EOS_MGM_URL: $SWAN_EOS_PROJ_MGM
    EOS_PATH: $SWAN_EOS_PROJ_BASE_PATH/public/Gallery/
  image: gitlab-registry.cern.ch/ci-tools/ci-web-deployer
  script: deploy-eos
  only: 
    - web
  when: on_success